# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'TrainHelper' do
pod 'Alamofire', '~> 3.2.0'
pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
pod 'SWXMLHash', '~> 2.3.0'
pod 'AMap2DMap'
pod 'AMapSearch'
end

target 'TrainHelperTests' do

end

target 'TrainHelperUITests' do

end

